scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
      
  # https://docs.docker.com/config/daemon/prometheus/
  - job_name: "docker"
    static_configs:
      - targets: ["host.docker.internal:9323"]

  - job_name: "traefik"
    static_configs:
      - targets: ["traefik:8080"]
  - job_name: "endlessh"
    static_configs:
      - targets: ["endlessh:2112"]
