tcp:
  routers:
    nas:
      rule: HostSNI(`{{ env "NAS_NAME" }}.synology.me`) || HostSNIRegexp(`^.*\.{{ env "NAS_NAME" }}.synology.me$`)
      service: nas
      entryPoints:
        - websecure
      tls:
        passthrough: true
  services:
    nas:
      loadBalancer:
        servers:
          - address: 192.168.1.31:443